fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    mysql: git://github.com/puppetlabs/puppetlabs-mysql.git
    java7: git://github.com/softek/puppet-java7.git
  symlinks:
    jira: "#{source_dir}"
