name          'puppet-jira'
version       '0.0.1'
source        'UNKNOWN'
author        'Anton Lindstrom'
license       'MIT'
summary       'Module to install Atlassian JIRA'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'maestrodev/wget', '>= 1.2.2'
dependency 'softek/java7', '>= 0.1.0'
